
const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO _3DFunction2[] = 
{
    {BACK_SUB_MODE_3D3,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_7_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_7_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    
    {BACK_SUB_MODE_3D3,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_7,5},
    
    {BACK_SUB_MODE_3D3,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_7_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_7_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    /********************************************/
    
    
    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},  
    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_SHOULDER,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    
    
    /*******************************************/
    
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
    {BACK_SUB_MODE_3D3,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,5},
};