
const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO DemoFunction[] = 
{
  {BACK_SUB_MODE_3D1,WALK_LOCATE_ABSULATE,370,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_7,10},
  {BACK_SUB_MODE_3D1,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,30},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
 
  {BACK_SUB_MODE_3D1,WALK_LOCATE_ABSULATE,320,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_7,10},
  {BACK_SUB_MODE_3D1,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,30},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
  
  {BACK_SUB_MODE_3D1,WALK_LOCATE_ABSULATE,250,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_7,10},
  {BACK_SUB_MODE_3D1,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,30},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
  
  {BACK_SUB_MODE_3D1,WALK_LOCATE_ABSULATE,200,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_7,10},
  {BACK_SUB_MODE_3D1,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,30},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
  
  {BACK_SUB_MODE_3D1,WALK_LOCATE_ABSULATE,150,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_7,10},
  {BACK_SUB_MODE_3D1,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,30},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
  
  {BACK_SUB_MODE_3D1,WALK_LOCATE_ABSULATE,100,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_7,10},
  {BACK_SUB_MODE_3D1,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,30},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
  
  {BACK_SUB_MODE_3D1,WALK_LOCATE_ABSULATE,50,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_7,10},
  {BACK_SUB_MODE_3D1,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,30},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
  
  {BACK_SUB_MODE_3D1,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_7,10},
  {BACK_SUB_MODE_3D1,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,30},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
  
};


