#ifndef __ALL_H__
#define __ALL_H__

#include <string.h>
#include <stdio.h>
#include "efm32.h"
#include "em_cmu.h"
#include "em_chip.h"
#include "em_gpio.h"
#include "EFM32_def.h"
#include "EFM32_types.h"
#include "em_assert.h"
#include "main.h"

#include "ControlBox.h"
#include "backaction.h"
#include "autoFunction0.c"
#include "autoFunction1.c"
#include "autoFunction2.c"
#include "autoFunction3.c"
#include "autoFunction4.c"
#include "autoFunction5.c"

#include "autoFunction7.c"
#include "autoFunction8.c"
#include "autoFunction9.c"

#include "DemoFunction.c"
#include "_3DFunction0.c"
#include "_3DFunction1.c"
#include "_3DFunction2.c"
#include "AutoFunctionStretch.c"

#include "airbagaction.h"

#include "ADC_Scan.h"
#include "AxisMotor.h"
#include "BackPad.h"
#include "BlueTooth.h"
#include "Data_Cul.h"
#include "DMA_Ctrl.h"
#include "Flex_Uart.h"
#include "HandUart_New.h"
#include "IndicateLED.h"
#include "input.h"
#include "KnockMotor_8840.h"
#include "KneadMotor.h"
#include "LED_RGB.h"
#include "LegMotor.h"
#include "LegKnead_Uart.h"
#include "Mp3Ctrl.h" 
#include "memory.h"
#include "NetCloud.h"
#include "power.h"
#include "problem.h"   
#include "Roller_Uart.h"
#include "signalUart_new.h"
#include "SlideMotor.h"
#include "timer.h"
#include "testCommand.h"
#include "system.h"
#include "UartLeg.h"
#include "Valve.h"
#include "VoiceUart.h"
#include "WalkMotor.h"
#include "WaistHot.h"
#include "xmodem.h"
#include "BackPad.h"
#include "SingleLine.h"
#include "Rock.h"

#endif

