#ifndef __PROBLEM__H__
#define __PROBLEM__H__
void Problem_Initial_IO(void);
void Problem_10ms_Int(void);
void Problem_Proce(void);
bool Problem_Get3DFault(void);
bool Problem_GetFlexFault(void);
bool Problem_GetWalkSwitchFault(void);
#endif /*__PROBLEM__H__*/