//中医理疗  轻柔呵护
const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction8[] = 
{	
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PressNeck, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_5, _3D_PROGRAM, AXIS_STRONGEST, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 5, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 5, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_Ear, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 5, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 5, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_2, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 6, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 6, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_DEC_PULSE, 10, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, 0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 3, KNOCK_PWM, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_1_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 5 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
    //    
    //    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_1_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    
    //    //{ BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 5 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
    //    //=========================================肩颈部揉捏-手法1-指压=========================================--22
    //    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_1_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_3_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
    //    
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 2, KNOCK_PWM, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
    //    //=========================================背上部指压-揉捏-手法3=========================================--29
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_WAIST, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MAX, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_7_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 5 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_WAIST, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 5 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MAX, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_2, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 3, KNOCK_STOP, 0, 0, SPEED_1, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MAX, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
    //    //========================================背下-腰部部指压-揉捏-手法1=========================================--39
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MED, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    //    
    //    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    //=========================================背上部-指压-手法2=========================================--43
    //    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_8_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 5, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_WAIST, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 3, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 60, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_WAIST, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_8_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 5 },
    //    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 4 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_WAIST, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_4, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_8_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 60, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_WAIST, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_WEAKER, _3D_SPEED_2, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 6, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 40, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_1, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 60, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 100, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_WAIST, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 100, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 60, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 40, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 6, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 60, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 5 },
    //    //=========================================背下部-腰部-臀部-揉捏-手法2=========================================--77
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_2, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 5 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MAX, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 5 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 5 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MAX, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 5 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 5 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MAX, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 5 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    //=========================================肩颈部揉捏-指手法1-指压=========================================--93
    //    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_2_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_2_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 10, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    //=========================================背上部-指压-揉捏-手法2-手法1=========================================--100
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_NeckMed, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_DEC_PULSE, 10, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, 0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 3, KNOCK_PWM, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_DEC_PULSE, 10, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, 0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 3, KNOCK_PWM, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    //=========================================肩颈部揉捏-手法1--指压-手法3=========================================--110
    //    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_4_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_2_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 5, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_1_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_3_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 }
    //    //=========================================背上部揉捏-手法1-指压=========================================--116
    
    //归肩位，3D开背 回程先3D敲到80 3D顶到最高 然后敲击到130 再3D指压和敲击到肩1/10位置 避开两个位置的空敲
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},    
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_3D_PRESS,50 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_AUTO_WALK,0,_3D_SPEED_3,0},
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_3D_PRESS,80 ,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2,_3D_AUTO_WALK,0,_3D_SPEED_3,0},
    //    //{BACK_SUB_MODE_PRESS,WALK_LOCATE_3D_PRESS,80 ,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_AUTO_WALK,0,_3D_SPEED_3,0},
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2,_3D_PARK,0,0,0},   
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_3D_PRESS,SHOULDER_POSITION ,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1,_3D_AUTO_WALK,0,_3D_SPEED_3,0},
    //    //肩位-10,3D最高；宽-窄揉5次，3D换中位，搓背4次。6
    //    {BACK_SUB_MODE_PRESS,SHOULDER_DEC_PULSE,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    //    {BACK_SUB_MODE_KNEAD,WALK_PWM,0 ,KNEAD_RUN_MAX_MIN,5,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},//
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},//modifide AXIS_MIDDLE to AXIS_STRONGER
    //    {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PARK,0 ,KNEAD_RUN_RUBBING,12,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    //    //10--肩位-20，搓背2次，揉5圈停中位。10
    //    {BACK_SUB_MODE_PRESS,SHOULDER_DEC_PULSE,20 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PARK,0 ,KNEAD_RUN_RUBBING,6,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0}, 
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    //    //指压到肩+55，停两秒，中中揉。13
    //    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,55 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},//{BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,45 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    //    //减5，中中揉，到肩+10。15
    //    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_PRESS,WALK_DEC_PULSE,5 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    //    
    //    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_PRESS,WALK_DEC_PULSE,5 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    //    
    //    
    //    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //   //20
    //   {BACK_SUB_MODE_PRESS,WALK_DEC_PULSE,5 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    //    
    //    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_PRESS,WALK_DEC_PULSE,5 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    //    
    //    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_PRESS,WALK_DEC_PULSE,5 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    //    
    //    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_PRESS,WALK_DEC_PULSE,5 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    //    
    //    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_PRESS,WALK_DEC_PULSE,5 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    //    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},//ADD BY LXM
    //    //前面加一句“中中揉“，30
    //    //指压到肩，3D到最高；揉5圈停在中；3D变速推3-4-5-6 采取停留轻敲方案 高频敲击方案放在结尾段
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_RUN_STOP_AT_MED,5,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    //       
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_RUN,1,0,SPEED_1,_3D_PARK,0,0,10},
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    //    
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_RUN,1,0,SPEED_1,_3D_PARK,0,0,10},
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    //    
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
    //    //40
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_RUN,1,0,SPEED_1,_3D_PARK,0,0,10},
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    //    
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_6,20},
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_RUN,1,0,SPEED_1,_3D_PARK,0,0,10},
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    //    //调整到窄，3D指压到0。45
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_3D_PRESS,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_AUTO_WALK,2,_3D_SPEED_3,20}, 
    //    //ADD 3d 顶臀47 +吴工提议增加揉敲动作
    //    //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_AUTO_WALK,2,_3D_SPEED_3,20},
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    //    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
    //    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 2, KNOCK_PWM, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //    //速度1揉捏到60，宽窄揉3次。51
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,60,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD,0,KNEAD_MAX_MIN,3,KNOCK_STOP,0,0,SPEED_2,_3D_KNEAD,0,0,0},
    //    //上行15PULS，宽窄揉3次；循环5次到135。53
    //    {BACK_SUB_MODE_PRESS,WALK_ADD_PULSE,15 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PARK,0,0,0}, 
    //    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD,0,KNEAD_MAX_MIN,3,KNOCK_STOP,0,0,SPEED_2,_3D_KNEAD,0,0,0},
    //    
    //    {BACK_SUB_MODE_PRESS,WALK_ADD_PULSE,15 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PARK,0,0,0}, 
    //    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD,0,KNEAD_MAX_MIN,3,KNOCK_STOP,0,0,SPEED_2,_3D_KNEAD,0,0,0},
    //    
    //    {BACK_SUB_MODE_PRESS,WALK_ADD_PULSE,15 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PARK,0,0,0}, 
    //    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD,0,KNEAD_MAX_MIN,3,KNOCK_STOP,0,0,SPEED_2,_3D_KNEAD,0,0,0},
    //    
    //    {BACK_SUB_MODE_PRESS,WALK_ADD_PULSE,15 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PARK,0,0,0}, 
    //    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD,0,KNEAD_MAX_MIN,3,KNOCK_STOP,0,0,SPEED_2,_3D_KNEAD,0,0,0},
    //    
    //    {BACK_SUB_MODE_PRESS,WALK_ADD_PULSE,15 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PARK,0,0,0}, 
    //    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD,0,KNEAD_MAX_MIN,3,KNOCK_STOP,0,0,SPEED_2,_3D_KNEAD,0,0,0},
    //    
    //    
    //    //调中位，扣击到60。63
    //    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,60,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,1,4,SPEED_1,_3D_PARK,0,0,0},
    //    //速度1，揉锤同步，到130；3D，；stronger 揉锤10S。64
    //    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,130,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
    //    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100 ,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_1,_3D_PARK,0,0,0},//臀部揉敲10s
    //    //下行，速度1，揉捏到60；3速，揉4圈，停窄；5速搓3下。66
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,60,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_3,0},
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_RUN_STOP_AT_MIN,4,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PARK,0 ,KNEAD_RUN_RUBBING,12,KNOCK_STOP,0,0,SPEED_5,_3D_PARK,0,0,0},
    //    //3D，MIDDLE，揉捏速度1，上行20PULS，3速，揉4圈，停窄；5速搓3下;循环3次到120。69
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,80,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_RUN_STOP_AT_MIN,4,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PARK,0 ,KNEAD_RUN_RUBBING,12,KNOCK_STOP,0,0,SPEED_5,_3D_PARK,0,0,0},
    //    
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,100,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_RUN_STOP_AT_MIN,4,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PARK,0 ,KNEAD_RUN_RUBBING,12,KNOCK_STOP,0,0,SPEED_5,_3D_PARK,0,0,0},
    //    
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,120,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_RUN_STOP_AT_MIN,4,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PARK,0 ,KNEAD_RUN_RUBBING,12,KNOCK_STOP,0,0,SPEED_5,_3D_PARK,0,0,0},
    //    //3D，WEAKER，揉捏速度1，上行20PULS；3速，揉4圈，停窄；5速搓3下;循环1次到160。78
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,140,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
    //    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_RUN_STOP_AT_MIN,4,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    //    {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PARK,0 ,KNEAD_RUN_RUBBING,12,KNOCK_STOP,0,0,SPEED_5,_3D_PARK,0,0,0}, 
    //调整到窄位，3D,最高；速度1叩击到肩位。84
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,1,4,SPEED_1,_3D_PARK,0,0,0},
    //{BACK_SUB_MODE_WAVELET,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_1,_3D_PARK,0,0,0},
    //增加肩部按摩 八字揉颈和两次颈部提拉86
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
    
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD,0,KNEAD_MAX_MED,2,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_DEC_PULSE,8,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD,0,KNEAD_MAX_MED,2,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_DEC_PULSE,8,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD,0,KNEAD_MAX_MED,2,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,35,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PARK,0,0,0},  
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MAX,1,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_3,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MIN,1,KNOCK_STOP,0,0,SPEED_4,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,15,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_7,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,70,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_6,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_7,_3D_PARK,0,0,0},// 
    
    {BACK_SUB_MODE_KNEAD,SHOULDER_ADD_PULSE,30,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_3,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,15,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_7,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,70,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PARK,0,0,0},//
    //
    //从肩1/10开始 脊柱向下2/z10个肩，小拉伸；上移1/10个肩，重复10次，到60。105
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,10},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,10},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,10},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
    //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_3_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_3_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_7_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_8_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_7_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_8_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_WAIST,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_WAIST,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,140 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,100 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,60 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
    
    //指压到7/10肩位置；开背动作 从肩7/10 到肩部  151
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_7_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_3_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    //从肩部揉捏回腰部 从1 3  5 7 8 
    
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0 ,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_3_10,0 ,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0 ,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,3,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    //121
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_7_10,0 ,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,2,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    //{BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,3,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_8_10,0 ,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,1,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD_3,0,KNEAD_WALK_MED_MED_3D_3,3,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD_NECK_3,0,_3D_SPEED_1,0},
    
    //指压回肩 3D中 宽-中揉 4下 216
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,10},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,0,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD,0,KNEAD_MAX_MED,4,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    
    //指压至肩 刮划斜方肌动作 结束回肩 209
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD,0,KNEAD_MAX_MIN,3,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD,0,0,0},
    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,10,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_1,0},
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD,0,KNEAD_MAX_MIN,3,KNOCK_STOP,0,0,SPEED_7,_3D_KNEAD,0,0,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_3,0}, //
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_3,0},//
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,10}, //速度更改 1-4 时间2-1
    
    
    //揉扣同步，下行到肩腰1/10；调整到窄，叩击到70;中间1/10至2/10段 屏蔽肩胛骨（收到窄指压下行）之后揉扣同步，到70。219
    {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10,0,KNEAD_RUN,0,KNOCK_STOP,1,4,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //------------------------------------------肩胛骨屏蔽----------------------------------------------20171127
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP,0,KNOCK_RUN,1,4,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,70,KNEAD_RUN,0,KNOCK_RUN,1,4,SPEED_1,_3D_PARK,0,0,0},
    //揉扣同步上行到250,3D最低；窄位指压，到肩部。223
    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,250,KNEAD_RUN,0,KNOCK_RUN,1,4,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    //指压到肩+10，速度2，揉捏3圈，停在窄；循环1次。225
    {BACK_SUB_MODE_PRESS,SHOULDER_DEC_PULSE,10,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD,0,KNEAD_MAX_MIN,4,KNOCK_STOP,0,0,SPEED_2,_3D_KNEAD,0,0,0},
    
    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,10,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_KNEAD,STOP_WALK_KNEAD,0,KNEAD_MAX_MIN,4,KNOCK_STOP,0,0,SPEED_2,_3D_KNEAD,0,0,0},
    //在肩+10，窄位，3D最高位。249
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,0,0},
    //肩+20,中中揉；肩+15\20\25\30\35\40\45\50\中中揉。251
    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,15,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,20,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,25,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,30,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,35,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,40,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,45,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,50,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //揉捏中位，指压到，肩+55；调整到窄位。268
    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,55,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //指压到肩位 加入顶肩动作 并在最高处加入高频敲击270
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,5},
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_RUN,5,0,SPEED_3,_3D_PARK,0,0,10},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,5},
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_RUN,5,0,SPEED_3,_3D_PARK,0,0,10},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,5},
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_RUN,5,0,SPEED_3,_3D_PARK,0,0,10},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_6,5},
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_RUN,5,0,SPEED_3,_3D_PARK,0,0,10},
    //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
    // //283
};