////慕思助眠
//
//const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction1[] = 
//{	
//    //  /*****************************************test*****************************************/
//    //  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,    0, KNEAD_STOP_AT_MIN, 0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_1,0},
//    //  //配合左侧气囊摇摆
//    //  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,    0, KNEAD_STOP_AT_MIN, 0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_1,0},
//    //  {BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    //  {BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    //  {BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    //  {BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    //  {BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    //   {BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    //  {BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    //  {BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    //  {BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    // /*****************************************************************************************/
//    
//    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_NeckMed, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_1, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_2, 0 },
//    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 6, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_1, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 4, KNOCK_STOP, 0, 0, SPEED_1, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_2, 0 },
//    //=========================================肩颈部揉捏-手法1-=========================================--3
//    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_1_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN, 4, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 3, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    // { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 3, KNOCK_PWM, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 3, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    // { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 2, KNOCK_PWM, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PressNeck, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    
//    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MED, 0, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, SHOULDER_ADD_PULSE, 65, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
//    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,30,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
//    //=========================================背上部揉捏-手法2-手法3-指压=========================================--10
//    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_1_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    //10
//    //{ BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 5, KNOCK_PWM, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 4, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    
//    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    
//    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 4, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_DEC_PULSE, 10, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, 0, _3D_PARK,0, 0, 0 },
//    // { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 3, KNOCK_PWM, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MED, 0, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_2, 0 },
//    //=========================================背上部指压-揉捏-手法3-=========================================--18
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 8, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_Ear, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    //{ BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 8, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    //21
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 8, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    
//    //=========================================肩颈部指压-=========================================--25
//    // { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 8, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 }, 
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 8, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_Ear, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 5, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 5, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, _3D_5, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 }, 
//    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    
//    /*************************************************************************************/
//    
//    //敲击向下
//    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,5,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_7,0},
//    //窄推+顶 向上
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_STOP,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,    0, KNEAD_STOP_AT_MIN, 0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_1,0},
//    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,  65,KNEAD_STOP_AT_MIN,        0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_1,0},
//    //揉捏向下
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_STOP,10,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
//    //搓背向上
//    
//    
//    /*********************************************************************************41*/
//    //配合左侧气囊摇摆
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,    0, KNEAD_STOP_AT_MIN, 0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_1,0},
//    {BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    {BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    {BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    {BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    {BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    {BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    {BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    {BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    {BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
//    /*****************************************************************************************/
//    
//    
//    
//    
//    
//    
//    //搓背  
//    {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},
//    {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},
//    {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},
//    {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,_3D_3,_3D_SPEED_7,0},
//    {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},
//    
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,_3D_3,_3D_SPEED_4,10},
//    //  {BACK_SUB_MODE_SOFT_KNOCK,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_7,0},
//    //  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,1,4,SPEED_4,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_7,0},
//    //  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_7,0},
//    //  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_7,0},
//    //  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_7,0},
//    
//    
//    
//    //按摩肩部
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_WAIST,0,KNEAD_RUN_STOP,10,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
//    
//    //颈部指压到顶
//    //指压到颈部
//    //指压+顶2次
//    //颈部
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,    0, KNEAD_STOP_AT_MIN, 0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_1,0},
//    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,  65,KNEAD_STOP,        0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_1,0},
//    {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0, KNEAD_STOP,        0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
//    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,  65,KNEAD_STOP,        0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_1,0},
//    {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0, KNEAD_STOP,        0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
//    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,  65,KNEAD_STOP,        0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_1,0},
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,    0, KNEAD_STOP_AT_MED, 0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_1,0},
//    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,    0, KNEAD_STOP,        0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,  _3D_SPEED_4,0},
//    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,    0, KNEAD_STOP,        0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_5,_3D_SPEED_4,0},
//    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,    0, KNEAD_STOP,        0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,  _3D_SPEED_4,0},
//    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,    0, KNEAD_STOP,        0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_5,_3D_SPEED_4,0},
//    {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0, KNEAD_STOP,        0,KNOCK_STOP,0,0,SPEED_3,_3D_PARK,0,0,0},
//    
//    //揉捏向下
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_STOP,10,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,_3D_2,_3D_SPEED_7,0},
//    // //窄推+顶 向上
//    //  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,    0, KNEAD_STOP_AT_MIN, 0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,_3D_5,_3D_SPEED_1,0}
//    // //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
//    
//    
//    //臀部顶起5S
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,_3D_5,_3D_SPEED_5,50},
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,10},
//    // 揉臀6s 
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_STOP,6,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//    //向上揉到肩
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_WAIST,0,KNEAD_RUN_STOP,10,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,_3D_2,_3D_SPEED_1,0},
//    //窄推下
//    {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
//    //窄推上。
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,    0, KNEAD_STOP_AT_MIN, 0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_1,0},
//    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,  65,KNEAD_STOP_AT_MIN,        0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_1,0},
//    //肩颈部位
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 }, 
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 8, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_Ear, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 5, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 5, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, _3D_5, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 }, 
//    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    //---
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 }, 
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 8, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_Ear, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 5, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 5, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, _3D_5, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 }, 
//    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
//    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
//    
//    //   { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, _3D_5, _3D_SPEED_3, 0 },
//    //   { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
//    
//    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_1_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, _3D_5, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_1_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_3_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, _3D_5, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_3_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, _3D_5, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_7_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, _3D_5, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_7_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, _3D_5, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, _3D_5, _3D_SPEED_3, 0 },
//    { BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },   
//    //窄推+顶
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_STOP,2,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
//    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,    0, KNEAD_STOP_AT_MIN, 0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_1,0},
//    {BACK_SUB_MODE_PRESS,SHOULDER_ADD_PULSE,  65,KNEAD_STOP_AT_MIN,        0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_1,0},
//};
//
//////舒展按摩（宽幅度按摩）中等力度
////const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction1[] = 
////{	
////  //揉捶同步到肩部（低速）
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
////  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  
////  //指压到顶//10
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  //{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
//// {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
//// 
////  
////  //颈部组合
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  //搓背  
////  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
////
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,80,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  //腰部定点捶打//54
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,20,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,30,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,40,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  //等待
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,2,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,1,KNOCK_RUN_WIDTH,20,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,30,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,40,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  //等待
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,2,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  //揉捏定点
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  //局部揉捶同步//63
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,80,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
////  
////} ;
/////*************************************************************/


//舒展按摩（宽幅度按摩）中等力度
const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction1[] = 
{	
    //{BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0}, 
    
    //揉捶同步到肩部（低速）
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},	
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    
    
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},//ADD
    
    //指压到顶//10
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    //{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    //颈部组合
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    //搓背  
    {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,80,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    //腰部定点捶打//54
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,20,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,30,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,40,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    //等待
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,2,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MED,1,KNOCK_RUN_WIDTH,20,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,30,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,40,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    
    
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},//ADD
    
    //等待
    {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,2,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    //揉捏定点
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    //局部揉捶同步//63
    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,80,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
    {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
    
    
} ;
/*************************************************************/


