////腰椎舒缓
////const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction4[] = 
////{	
////  //揉捶同步到底部（低速）
////  /**************************/
////  /***************************/
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
////  /////////////////////////////////////////////////////////////////////////////
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
////
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////  //1
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////  //2
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////  //3
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
////  //4
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,80,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////  //5
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////  //6
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,80,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////  //7
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////  //8
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,80,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////  //9
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////  //10
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
////  //11
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_5},
////  //12
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,80,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
////  //13
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_5},
////  //14
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,80,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
////
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_1},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,1,4,SPEED_5},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_4},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,8,2,SPEED_4},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3},	
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},							
////  //modify 20130709
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_6},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_6},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,100,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,100,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
////  //modify 20130709
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_1},
////  
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
////  //modify 20130709
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
////  
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
////  ////////////////////////////////////////////////////////////////////////////
////  //modify 20130709
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
////  
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},	
////  //肩部捶打
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN_STOP,8,2,SPEED_3},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,7,3,SPEED_3},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,6,4,SPEED_4},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,5,5,SPEED_5},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,1,4,SPEED_6},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,1,4,SPEED_6},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_4},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,8,2,SPEED_4},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,9,1,SPEED_3},
////  /*******************************************************************************/
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,5,KNEAD_RUN_STOP_AT_MAX,2,KNOCK_STOP,0,0,SPEED_2},
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2},
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},
////  /******************************************************************************/
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,25,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4},
////  //捶击定位（窄中宽）
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4},
////  //捶击定位（窄中宽）
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_6},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_6},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
////  //揉捏
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_5},
////  //向上行走15，捶击定位（窄）
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,15,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},	
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},	
////  //向上行走15，捶击定位（窄）
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},	
////  //向上行走15，捶击定位（窄）80
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,45,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},	
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},	
////  //向上行走15，捶击定位（窄）
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,60,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},	
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},	
////  //向下揉捏到底
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_6},
////  //定点轻敲5次
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,25,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_5},	
////  //轻敲到顶部
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},	
////  //定点低速揉捏5
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_1},
////  //向下捶击行走到肩部	////
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},		
////  //定点捶击2秒
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,20,0,SPEED_1},
////  //向上捶击行走到顶部	100
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},		
////  //定点捶击2秒
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,KNOCK_STOP,20,0,SPEED_1},
////  //向下捶击行走到肩部	
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},		
////  //定点捶击2秒
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,20,0,SPEED_1},	
////  //定点揉捏5
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3},
////  //向下捶击行走到底	
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,4,KNOCK_STOP,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4},
////  //向上揉捶行走25/115
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,25,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,50,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
////  //向下揉捏到底
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4},
////  //变速揉摧同步到底
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,60,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
////  //定点揉捏5
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_4},
////  //窄指压到顶
////  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1},
////  
////  //070315测试/133
////  //低速敲打到底部/141
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2},		
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3},		
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,80,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3},		
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,40,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_4},		
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_5},		
////  //腰部变速敲打161
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,5,KNOCK_STOP,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_5},
////  //行走揉摧同步182
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_6},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_5},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,80,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
////  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
////  //轻敲到肩部//208
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},	
////  //轻敲到顶部
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},	
////  //轻敲
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},
////  //轻敲
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,60,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},	
////  //轻敲
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},	
////  //轻敲
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},	
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,25,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_5},	
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,25,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_6},	
////  //揉捏到顶/217
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,80,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,BUTTOCKS_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
////  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
////  //变换幅度的轻敲/222
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_STOP_AT_MED,1,KNOCK_RUN_STOP,1,4,SPEED_4},	
////  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_STOP_AT_MIN,1,KNOCK_RUN_STOP,1,4,SPEED_3}
////};
//
//
//
//
//
//const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction4[] = 
//{	
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  
//  
//  
//  
//  /***************************************************************************/
// {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
// {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
// {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
// {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_3,0},
///****************************************************************************/
//  
//  
////		//揉捶同步到底部（低速）
////		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
////		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
////		/////////////////////////////////////////////////////////////////////////////
////		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
////		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
////		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
////		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
////		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
////		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
////                
////                
////
////		{BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////		//1
////		{BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////		//2
////		{BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////		//3
////		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
////		//4
////		{BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////		//5
////		{BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////		//6
////		{BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////		//7
////		{BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////		//8
////		{BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////		//9
////		{BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
////		//10
////		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
////		//11
////		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_5},
////		//12
////		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,80,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
////		//13
////		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_5},
////		//14
////		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,80,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//                
//                
//
//                
//                //搓背  
////  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
////  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//
//
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_1},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,1,4,SPEED_5},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_4},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,8,2,SPEED_4},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3},	
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},							
//                //modify 20130709
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_6},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_6},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,100,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,100,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//                
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_1},
//                
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//                
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//                
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		////////////////////////////////////////////////////////////////////////////
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},	
//		//肩部捶打
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN_STOP,8,2,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,7,3,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,6,4,SPEED_4},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,5,5,SPEED_5},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,1,4,SPEED_6},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,1,4,SPEED_6},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_4},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,8,2,SPEED_4},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,9,1,SPEED_3},
//		//Neck Knead
//		////
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},		
//
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,5,KNEAD_RUN_STOP_AT_MAX,2,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},
//                
//                //搓背  
////  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
////  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//
//                
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+25,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4},
//		//捶击定位（窄中宽）
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4},
//		//捶击定位（窄中宽）
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_6},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_6},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
//		//揉捏
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_5},
//		//向上行走15，捶击定位（窄）
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+15,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},	
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},	
//		//向上行走15，捶击定位（窄）
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},	
//		//向上行走15，捶击定位（窄）80
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+45,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},	
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},	
//		//向上行走15，捶击定位（窄）
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+60,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},	
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},	
//		//向下揉捏到底
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_6},
//		//定点轻敲5次
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,25,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_5},	
//		//轻敲到顶部
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},	
//		//定点低速揉捏5
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_1},
//		//向下捶击行走到肩部	////
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},		
//		//定点捶击2秒
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,20,0,SPEED_1},
//		//向上捶击行走到顶部	100
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},		
//		//定点捶击2秒
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,KNOCK_STOP,20,0,SPEED_1},
//		//向下捶击行走到肩部	
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},		
//		//定点捶击2秒
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,20,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},		
//		//定点揉捏5
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3},
//		//向下捶击行走到底	
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,4,KNOCK_STOP,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4},
//		//向上揉捶行走25/115
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+25,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+50,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
//		//向下揉捏到底
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4},
//		//变速揉摧同步到底
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+60,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
//		//定点揉捏5
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_4},
//		//窄指压到顶
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1},
//		
//		//070315测试/133
//		//颈部动作组合
//		
//		/*
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},		
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},		
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},		
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},		
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},		
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2},
//		//低速敲打到底部/141
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},		
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2},		
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_NeckMed,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2},		
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3},		
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3},		
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+40,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_4},		
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_5},	
//                
//                //搓背  
////  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
////  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//
//                
//		//腰部变速敲打161
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,5,KNOCK_STOP,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_5},
//		//行走揉摧同步182
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_6},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		//颈部动作组合194
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,1,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		//轻敲到肩部//208
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},	
//		//轻敲到顶部
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},	
//		//轻敲
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},	
//		//轻敲			////////////////////////////////////
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},	
//		//轻敲
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+60,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},	
//		//轻敲
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},	
//		//轻敲
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},	
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,25,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_5},	
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,25,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_6},	
//		//揉捏到顶/217
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		//变换幅度的轻敲/222
//		//轻敲到肩部
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},	
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN_STOP_AT_MED,1,KNOCK_RUN_STOP,1,4,SPEED_4},	
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_TOP,0,KNEAD_RUN_STOP_AT_MIN,1,KNOCK_RUN_STOP,1,4,SPEED_3}	,*/
//	
//};
//
//
//

const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction4[] = 
{	
  
 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
 
  
    //颈部来回揉捏		
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed ,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},

  //上提   揉捏宽度：窄 窄 揉
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed  ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP_AT_MED  ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK    ,10,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},

  //上提   揉捏宽度：MED MED 揉
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed  ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP_AT_MED  ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK    ,10,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},






//add 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},



//end 


  //上提   揉捏宽度：窄 窄 揉

 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
 
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,10,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP_AT_MED         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},


  //上提   揉捏宽度：MED MED 揉
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed  ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP_AT_MED  ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK    ,10,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},




//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,10,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
 //add 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0}, 
 //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},


//end 
 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
 
 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},



//end 



  //上提   揉捏宽度：窄
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
 //add 
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},

//end 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
 //add 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},



//end 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
 //
 {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,3,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},

  // 第 3 节 MIN/////////////////////////////////////////////////////////
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_2,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},//ADD

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},

  // 第 3 节 MIN/////////////////////////////////////////////////////////
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_5,_3D_PROGRAM,_3D_5,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},





  
  //滑肩  肩部抚摸  揉捏宽度：中
   {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},



  //滑肩  肩部抚摸  揉捏宽度：窄
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
 





  
  //滑肩  肩部抚摸  揉捏宽度：宽
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},

//MIN
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,1,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,1,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},

  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK       ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
  
  //指压到顶
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PressNeck,0,KNEAD_STOP           ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK     ,0,KNEAD_RUN_STOP_AT_MIN,1,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP           ,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK     ,0,KNEAD_STOP           ,0,KNOCK_RUN,40,0,SPEED_4,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK     ,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  

  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP           ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK     ,20,KNEAD_RUN_STOP_AT_MAX,1,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP           ,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK     ,20,KNEAD_STOP           ,0,KNOCK_RUN,40,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK     ,0,KNEAD_RUN_STOP_AT_MAX,3,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
 


//
  //颈部来回揉捏		
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed ,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  

 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
 


  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},



  //搓背  
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},

  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_6_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //WALK_SHOULDER_WAIST_5_10  WALK_LOCATE_SHOULDER
  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_3_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},




  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_6_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //WALK_SHOULDER_WAIST_5_10  WALK_LOCATE_SHOULDER
  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_3_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},



  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},

  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,1,4,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,8,2,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},	
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
  //肩部捶打
  {BACK_SUB_MODE_KNEAD     ,WALK_LOCATE_PARK, 0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP       ,0,KNOCK_RUN_STOP,8,2,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,7,3,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,6,4,SPEED_4,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,5,5,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,6,4,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,6,4,SPEED_6,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  // 第 3 节 MIN/////////////////////////////////////////////////////////
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},

  //捶击定位（窄中宽）
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //捶击定位（窄中宽）
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
/////////////

};

