//大师精选
const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction7[] = //STATE_RUN_PWM_ABS
{  
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_NeckMed, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_1, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 6, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_1, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 4, KNOCK_STOP, 0, 0, SPEED_1, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
    //=========================================肩颈部揉捏-手法1-=========================================--3
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_2_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN, 4, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 3, KNOCK_PWM, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 2, KNOCK_PWM, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PressNeck, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MED, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, SHOULDER_ADD_PULSE, 65, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    {BACK_SUB_MODE_KNEAD,STATE_RUN_LOCATE_POSITION,0,KNEAD_MED_STOP_MED,30,KNOCK_STOP,0,0,SPEED_1,_3D_PARK,0,0,0},
    //=========================================背上部揉捏-手法2-手法3-指压=========================================--10
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_1_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    //10
    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 5, KNOCK_PWM, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 4, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 4, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_DEC_PULSE, 10, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, 0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 3, KNOCK_PWM, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MED, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
    //=========================================背上部指压-揉捏-手法3-=========================================--18
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 8, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_Ear, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //{ BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 8, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    //21
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 8, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    
    //=========================================肩颈部指压-=========================================--25
    // { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 8, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 }, 
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 8, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_Ear, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 5, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 5, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 }, 
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //=========================================肩颈部指压-手法2-=========================================--35
    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_2_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_2, 0 },
    //=========================================背上部指压-=========================================36
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_3, 0 },
    //30
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 6, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
    
    //=========================================肩颈部指压-手法1-=========================================
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_3_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 3, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_4_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_2_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_4_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 }, //51
    //=========================================背上部揉捏-=========================================-
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_WAIST, 0, KNEAD_RUBBING, 5, KNOCK_PWM, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    //=========================================背下部揉捏=========================================-48
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_3_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKER, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_2, 0 },
    //40
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //0606
    
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_WAIST, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKER, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_WAIST, 0, KNEAD_RUBBING, 5, KNOCK_PWM, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
    //END
    //=========================================背上部揉捏-手法2========================================--51
    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_WEAKER, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_7_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_WEAKER, _3D_SPEED_3, 0 },
    
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_WAIST, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
    //0606
    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_WAIST, 0, KNEAD_RUBBING, 5, KNOCK_PWM, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    //END
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 3, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_4_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_WEAKER, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_WAIST, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_WEAKER, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_2, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP_AT_MIN, 5, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_WAIST, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_WAIST, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_WAIST, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKER, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_6_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    //=========================================背下部指压-手法1-揉捏=========================================--69
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_WAIST, 0, KNEAD_RUBBING, 5, KNOCK_PWM, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 2, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 90, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 2, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    //=========================================背下部臀部揉捏=========================================--73
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_ABSULATE, 110, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 2, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_WAIST, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 2, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_WAIST, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 2, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    //0606
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_ABSULATE, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    
    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_WAIST, 0, KNEAD_RUBBING, 5, KNOCK_PWM, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    //END
    
    //=========================================腰部揉捏=========================================--79
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 2, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_8_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 2, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_7_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 2, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_6_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP_AT_MAX, 2, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGEST, 0, 0 },
    
    { BACK_SUB_MODE_SOFT_KNOCK, WALK_SHOULDER_WAIST_2_10, 0, KNEAD_STOP, 0, KNOCK_RUN, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    
    { BACK_SUB_MODE_SOFT_KNOCK, WALK_SHOULDER_WAIST_9_10, 0, KNEAD_STOP, 0, KNOCK_RUN, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MAX, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_SOFT_KNOCK, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_RUN, 30, 0, SPEED_1, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
    
    { BACK_SUB_MODE_SOFT_KNOCK, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_RUN, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    
    { BACK_SUB_MODE_SOFT_KNOCK, WALK_LOCATE_WAIST, 0, KNEAD_STOP, 0, KNOCK_RUN, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MAX, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
    //=========================================整背部敲击=========================================95
    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_7_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_SHOULDER_WAIST_3_10, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_2, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_WAIST, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKER, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PROGRAM, AXIS_WEAKEST, _3D_SPEED_3, 0 },
    
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 0 },
    //=========================================背部指压=========================================98
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN_STOP, 5, KNOCK_STOP, 0, 0, SPEED_1, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_RUN, 3, KNOCK_STOP, 0, 0, SPEED_1, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 0 },
    //=========================================肩颈部指压-揉捏=========================================102
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_2_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 3, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 3, KNOCK_PWM, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 2, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 2, KNOCK_PWM, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_NeckMed, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 5, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_SHOULDER, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_TOGGLE, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_DEC_PULSE, 10, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, 0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_WAVELET, WALK_LOCATE_PARK, 0, KNEAD_RUBBING, 2, KNOCK_PWM, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MED, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    //=========================================背上部肩颈部揉捏-手法3-手法2=========================================114
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_6, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_Ear, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_3, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 10 },
    { BACK_SUB_MODE_KNEAD, WALK_LOCATE_PARK, 0, KNEAD_STOP_AT_MIN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PressNeck, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 1, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 10 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_NeckMed, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_SHOULDER, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD, RUN_UP_DOWN, 0, KNEAD_FITFUL, 4, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGEST, _3D_SPEED_2, 10 },
    //=========================================肩颈部指压-手法1=========================================129
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_2_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_KNEAD,RUN_UP_DOWN, 0, KNEAD_TOGGLE, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_STRONGER, _3D_SPEED_2, 5 },
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_5_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_2, _3D_PARK,0, 0, 0 },
    { BACK_SUB_MODE_PRESS, WALK_LOCATE_PARK, 0, KNEAD_STOP, 0, KNOCK_STOP, 0, 0, SPEED_0, _3D_PROGRAM, AXIS_MIDDLE, _3D_SPEED_2, 5 },
    { BACK_SUB_MODE_KNEAD, WALK_SHOULDER_WAIST_2_10, 0, KNEAD_RUN, 0, KNOCK_STOP, 0, 0, SPEED_3, _3D_PARK,0, 0, 0 }
    //=========================================背上部揉捏-指压=========================================135
};
